server:
  port: 8082

spring:
  application:
    name: Server-Provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://mrbird:123456@localhost:8080/eureka/
      #可集群
      #defaultZone: http://mrbird:123456@localhost:8080/eureka/,http://mrbird:123456@peer2:8081/eureka/