server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: 17681102655@163.com
    #邮箱的授权码
    password: 1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true